input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][target_index]" => "synapsehub-%{service}-%{+YYYY.MM.dd}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "synapsehub-generic-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout { codec => rubydebug }
}